# Generated by Django 4.2.9 on 2025-01-30 00:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=50, null=True)),
                ("descripcion", models.TextField(max_length=100)),
                ("mail", models.EmailField(blank=True, max_length=50, null=True)),
                (
                    "estado_respuesta",
                    models.CharField(
                        choices=[
                            ("Contestada", "Contestada"),
                            ("No contestada", "No contestada"),
                            ("En proceso", "En proceso"),
                        ],
                        default="No contestada",
                        max_length=15,
                    ),
                ),
                ("celular", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "fecha",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta", models.TextField(max_length=100)),
                (
                    "fecha",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacto.consulta",
                    ),
                ),
            ],
        ),
    ]
