# Generated by Django 4.2.9 on 2025-01-30 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de publicacion",
                    ),
                ),
                (
                    "costo_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Automatizacion", "Automatizacion"),
                            ("Chatbots", "Chatbots"),
                            ("Limpieza de Datos", "Limpieza de Datos"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="servicios/%Y/%m/%d"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                        default="Activo",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
