# Generated by Django 4.2.9 on 2025-03-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="ventajas",
            field=models.TextField(blank=True, null=True),
        ),
    ]
