# Generated by Django 4.2.9 on 2025-05-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0002_servicio_ventajas"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
