# Generated by Django 4.2.9 on 2025-01-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=255)),
                ("contacto", models.CharField(max_length=255)),
                ("direccion", models.TextField()),
                ("fecha_registro", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
