# Generated by Django 4.2.9 on 2025-02-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0002_logactividad"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="estado",
            field=models.CharField(
                choices=[
                    ("vigente", "Vigente"),
                    ("pronto_a_vencer", "Pronto a Vencer"),
                    ("vencido", "Vencido"),
                ],
                default="vigente",
                max_length=20,
            ),
        ),
    ]
