# Generated by Django 4.2.9 on 2025-03-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratos", "0003_contrato_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrato",
            name="costo_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
